# Generated by Django 4.0.3 on 2022-03-23 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_actividad', models.CharField(max_length=50)),
                ('nombre_actividad', models.CharField(max_length=80)),
                ('programa', models.CharField(max_length=50)),
                ('cma', models.IntegerField()),
                ('caa', models.IntegerField()),
                ('cda', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_planilla', models.CharField(max_length=45)),
                ('nombre_planilla', models.CharField(max_length=50)),
                ('nombre_actividad', models.CharField(max_length=80)),
                ('cmp', models.IntegerField()),
                ('cap', models.IntegerField()),
                ('cdp', models.IntegerField()),
                ('actividad_id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='PPL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('td', models.IntegerField()),
                ('nui', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('documento', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('fase_tratamiento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=50)),
                ('descripcion_proyecto', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patio', models.CharField(max_length=45)),
                ('piso', models.IntegerField()),
                ('pasillo', models.IntegerField()),
                ('celda', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PPLxUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ubicacion', models.DateField()),
                ('estado', models.CharField(max_length=30)),
                ('PPL_id_ppl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.ppl')),
                ('Ubicacion_id_ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='PPLxPlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=30)),
                ('fehca_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('PPL_id_PPL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.ppl')),
                ('planilla_id_planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.planilla')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='proyecto_id_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.proyecto'),
        ),
    ]
