# Generated by Django 4.0.3 on 2022-04-28 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0006_patio_alter_actividad_id_alter_planilla_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatioxPlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupo_maximo', models.IntegerField()),
                ('cupos_asignados', models.IntegerField()),
                ('patio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.patio')),
                ('planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.planilla')),
            ],
        ),
    ]
