# Generated by Django 3.0.5 on 2022-05-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0009_auto_20220510_0852'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatioxPlanilla',
        ),
    ]
