# Generated by Django 3.0.5 on 2022-05-10 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0010_delete_patioxplanilla'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatioxPlanilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupo_maximo', models.IntegerField()),
                ('cupos_asignados', models.IntegerField()),
                ('patio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Patio')),
                ('planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Planilla')),
            ],
        ),
    ]
